-- Seed & Verification Queries for TruthForge-AI Initial Schema
-- Execute after applying 000001_initial_schema.sql

-- 1. Insert User Query
INSERT INTO queries (id, query_text, detected_domain, status)
VALUES (
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'Does mRNA vaccine technology induce long-term cellular immunity against viral respiratory infections?',
    'biomedical',
    'completed'
);

-- 2. Insert Verification Report (1:1 with query)
INSERT INTO reports (id, query_id, executive_summary, overall_confidence, report_status)
VALUES (
    'b1fbc999-9c0b-4ef8-bb6d-6bb9bd380a22',
    'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'Multiple peer-reviewed clinical studies confirm robust T-cell and memory B-cell responses generated by mRNA vaccines.',
    0.9250,
    'completed'
);

-- 3. Insert Claims Extracted from Report
INSERT INTO claims (id, report_id, claim_text, confidence_score, verification_status, explanation)
VALUES 
(
    'c2fdc999-9c0b-4ef8-bb6d-6bb9bd380a33',
    'b1fbc999-9c0b-4ef8-bb6d-6bb9bd380a22',
    'mRNA-1273 and BNT162b2 elicit persistent CD4+ and CD8+ memory T-cell responses lasting beyond 6 months.',
    0.9500,
    'verified',
    'Directly corroborated by flow cytometry longitudinal data across multiple clinical cohorts.'
),
(
    'c3fdc999-9c0b-4ef8-bb6d-6bb9bd380a44',
    'b1fbc999-9c0b-4ef8-bb6d-6bb9bd380a22',
    'Germinal center B-cell responses persist for up to 12 weeks post-boost.',
    0.9000,
    'verified',
    'Confirmed via fine-needle aspirates of draining lymph nodes.'
);

-- 4. Insert Canonical Sources (Decoupled, reusable across claims/reports)
INSERT INTO sources (id, source_name, source_url, publisher, source_type, trust_score, publication_date, doi)
VALUES 
(
    'd4fee999-9c0b-4ef8-bb6d-6bb9bd380a55',
    'Long-term SARS-CoV-2 Memory T Cells Induced by mRNA Vaccination',
    'https://doi.org/10.1016/j.cell.2021.08.015',
    'Cell Press',
    'journal',
    0.9800,
    '2021-09-01T00:00:00Z',
    '10.1016/j.cell.2021.08.015'
),
(
    'd5fee999-9c0b-4ef8-bb6d-6bb9bd380a66',
    'SARS-CoV-2 mRNA Vaccines Induce Persistent Germinal Centre Responses',
    'https://doi.org/10.1038/s41586-021-03738-2',
    'Nature Publishing Group',
    'journal',
    0.9900,
    '2021-06-28T00:00:00Z',
    '10.1038/s41586-021-03738-2'
);

-- 5. Link Claims to Sources via claim_sources Junction Table (M:N)
INSERT INTO claim_sources (id, claim_id, source_id, relevance_score)
VALUES 
(
    'e6aff999-9c0b-4ef8-bb6d-6bb9bd380a77',
    'c2fdc999-9c0b-4ef8-bb6d-6bb9bd380a33',
    'd4fee999-9c0b-4ef8-bb6d-6bb9bd380a55',
    0.9700
),
(
    'e7aff999-9c0b-4ef8-bb6d-6bb9bd380a88',
    'c3fdc999-9c0b-4ef8-bb6d-6bb9bd380a44',
    'd5fee999-9c0b-4ef8-bb6d-6bb9bd380a66',
    0.9600
);

-- 6. Insert Evidence Lineage (Micro-traceability)
INSERT INTO evidence_lineage (id, claim_id, source_id, claim_source_id, page_number, paragraph_number, sentence_number, quoted_text)
VALUES 
(
    'f7bff999-9c0b-4ef8-bb6d-6bb9bd380a99',
    'c2fdc999-9c0b-4ef8-bb6d-6bb9bd380a33',
    'd4fee999-9c0b-4ef8-bb6d-6bb9bd380a55',
    'e6aff999-9c0b-4ef8-bb6d-6bb9bd380a77',
    4,
    2,
    1,
    'Vaccine-induced spike-specific CD4+ and CD8+ T cells remained detectable in 100% of participants 6 months post-second dose.'
),
(
    'f8bff999-9c0b-4ef8-bb6d-6bb9bd380b00',
    'c3fdc999-9c0b-4ef8-bb6d-6bb9bd380a44',
    'd5fee999-9c0b-4ef8-bb6d-6bb9bd380a66',
    'e7aff999-9c0b-4ef8-bb6d-6bb9bd380a88',
    2,
    5,
    3,
    'Germinal center B cell frequencies peaked at week 4 and persisted for up to 12 weeks after the booster dose.'
);
